- ibexa/commerce/3.3/config/packages/ezplatform_site_factory.yaml
- ibexa/commerce/4.0/config/packages/ibexa_site_factory.yaml
- ibexa/experience/3.3/config/packages/ezplatform_site_factory.yaml
- ibexa/experience/4.0/config/packages/ibexa_site_factory.yaml
JIRA ref: https://issues.ibexa.co/browse/IBX-2573
https://github.com/ezsystems/ezplatform-site-factory/pull/158
> IBX-2573: Change default placeholder image for site factory template

- ibexa/commerce/4.1/manifest.json
- ibexa/content/4.1/manifest.json
- ibexa/experience/4.1/manifest.json
- ibexa/measurement/4.1/manifest.json
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-414](https://issues.ibexa.co/browse/IBX-414)
| **Requires**                             | ibexa/content#35, ibexa/measurement#2
| **Type**                                   | feature
| **Target Ibexa version** | `v4.1`
These are recipes for [`ibexa/measurement`](https://github.com/ibexa/measurement) package containing IbexaMeasurementBundle.
Target: Ibexa DXP 4.1 (Content, Experience, Commerce).
Mergable once the package is ready (contains merged in MVP) - PR will change status from draft to ready.
> [DO NOT MERGE] IBX-414: Created recipes for ibexa/measurement package

- ibexa/commerce/4.2/config/packages/ibexa.yaml
- ibexa/experience/4.2/config/packages/ibexa.yaml
Solves https://issues.ibexa.co/browse/IBX-3233
> [experience,commerce] Added language configuration to Corporate SA

- ibexa/commerce/4.2/config/routes/ibexa_corporate_account.yaml
- ibexa/experience/4.2/config/routes/ibexa_corporate_account.yaml
JIRA: https://issues.ibexa.co/browse/IBX-3603
> IBX-3603: corporate_portal --> customer_portal

- ibexa/cdp/3.3/config/packages/ibexa_cdp.yaml
- ibexa/cdp/3.3/config/routes/ibexa_cdp.yaml
- ibexa/cdp/3.3/manifest.json
- ibexa/cdp/4.2/config/packages/ibexa_cdp.yaml
- ibexa/cdp/4.2/config/routes/ibexa_cdp.yaml
- ibexa/cdp/4.2/manifest.json
- ibexa/commerce/3.3/config/packages/security.yaml
- ibexa/commerce/4.2/config/packages/security.yaml
- ibexa/content/3.3/config/packages/security.yaml
- ibexa/content/4.2/config/packages/security.yaml
- ibexa/experience/3.3/config/packages/security.yaml
- ibexa/experience/4.2/config/packages/security.yaml
> Issue: https://issues.ibexa.co/browse/IBX-3795
> [ibexa/cdp] IBX-3795: Added recipe for standalone ibexa/cdp package installation

- ibexa/commerce/4.3/config/packages/ibexa.yaml
- ibexa/commerce/4.3/manifest.json
- ibexa/experience/4.3/config/packages/ibexa.yaml
- ibexa/experience/4.3/manifest.json
Required by: https://github.com/ibexa/corporate-account/pull/106
> [ibexa/experience,commerce] Added configuration for Rate Limiter

- ibexa/commerce/4.3/config/packages/ibexa.yaml
- ibexa/commerce/4.3/config/packages/ibexa_admin_ui.yaml
- ibexa/content/4.3/config/packages/ibexa.yaml
- ibexa/content/4.3/config/packages/ibexa_admin_ui.yaml
- ibexa/experience/4.3/config/packages/ibexa.yaml
- ibexa/experience/4.3/config/packages/ibexa_admin_ui.yaml
> JIRA: https://issues.ibexa.co/browse/IBX-3729
> IBX-3729: Defined user content types

- ibexa/commerce/4.4/encore/package.json
- ibexa/content/4.4/encore/package.json
- ibexa/experience/4.4/encore/package.json
- ibexa/oss/4.4/encore/package.json
> [ibexa/*] Updated ckeditor to latest version

- ibexa/commerce/4.3/config/routes/ibexa_segmentation.yaml
- ibexa/commerce/4.4/config/routes/ibexa_segmentation.yaml
- ibexa/experience/4.3/config/routes/ibexa_segmentation.yaml
- ibexa/experience/4.4/config/routes/ibexa_segmentation.yaml
* https://github.com/ibexa/segmentation/pull/65
> IBX-4037: Added Segmentation REST endpoint

- ibexa/cart/4.4/manifest.json
- ibexa/commerce/4.4/manifest.json
These are recipes for [ibexa/cart](https://github.com/ibexa/cart) package containing IbexaCartBundle.
> Created recipes for ibexa/cart package

- ibexa/compatibility-layer/4.4/config/routes/deprecated/ibexa_compatibility_layer_commerce.yaml
- ibexa/compatibility-layer/4.4/config/routes/deprecated/ibexa_compatibility_layer_content.yaml
- ibexa/compatibility-layer/4.4/config/routes/deprecated/ibexa_compatibility_layer_experience.yaml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | IBX-3815
| **Type**                                   | feature
| **Target Ibexa version** | `v4.4`
| **BC breaks**                          | no
| **Doc needed**                       | yes
Fixed issue detected by CI: https://github.com/ibexa/experience/actions/runs/3761398117/jobs/6393116242
> IBX-3815: Fixed compatibility layer after legacy commerce clean up

- ibexa/commerce/4.4/config/routes/ibexa_cart.yaml
> JIRA: - 
Added ibexa/cart routing. Depends on https://github.com/ibexa/cart/pull/17
> Added ibexa/cart routing

- ibexa/commerce/4.4/config/routes/ibexa_cart.yaml
| Question                                  | Answer
| ----------------------------------------- | ------------------
| **JIRA issue**                            | [IBX-4397](https://issues.ibexa.co/browse/IBX-4397)
| **Type**                                  | feature 
| **Target Ibexa DXP version**              | `v4.4`
| **BC breaks**                             | no
Depends on https://github.com/ibexa/cart/pull/18
> IBX-4397: Added ibexa/cart REST routing

- ibexa/commerce/4.4/config/packages/ibexa.yaml
- ibexa/commerce/4.4/config/packages/ibexa_storefront.yaml
> JIRA: -
Added very basic storefront configuration
> Added basic storefront configuration

- ibexa/commerce/4.4/assets/scss/_header.scss
- ibexa/commerce/4.4/assets/scss/_main.scss
- ibexa/commerce/4.4/assets/scss/_training.scss
- ibexa/commerce/4.4/assets/scss/_tutorials.scss
- ibexa/commerce/4.4/templates/themes/standard/full/welcome_page.html.twig
- ibexa/commerce/4.4/templates/themes/standard/pagelayout.html.twig
- ibexa/content/4.4/assets/scss/_header.scss
- ibexa/content/4.4/assets/scss/_main.scss
- ibexa/content/4.4/assets/scss/_training.scss
- ibexa/content/4.4/assets/scss/_tutorials.scss
- ibexa/content/4.4/templates/themes/standard/full/welcome_page.html.twig
- ibexa/content/4.4/templates/themes/standard/pagelayout.html.twig
- ibexa/experience/4.4/assets/scss/_header.scss
- ibexa/experience/4.4/assets/scss/_main.scss
- ibexa/experience/4.4/assets/scss/_training.scss
- ibexa/experience/4.4/assets/scss/_tutorials.scss
- ibexa/experience/4.4/templates/themes/standard/full/welcome_page.html.twig
- ibexa/experience/4.4/templates/themes/standard/pagelayout.html.twig
- ibexa/oss/4.4/assets/scss/_header.scss
- ibexa/oss/4.4/assets/scss/_main.scss
- ibexa/oss/4.4/assets/scss/_training.scss
- ibexa/oss/4.4/assets/scss/_tutorials.scss
- ibexa/oss/4.4/templates/themes/standard/full/welcome_page.html.twig
- ibexa/oss/4.4/templates/themes/standard/pagelayout.html.twig
JIRA ref: https://issues.ibexa.co/browse/IBX-4952
> IBX-4952: Welcome screen RWD fixes

- ibexa/docker/4.5/manifest.json
JIRA: https://issues.ibexa.co/browse/IBX-4460
Using the latest tagged image from https://hub.docker.com/r/selenium/standalone-chrome/tags
All PRs:
https://github.com/ibexa/recipes-dev/pull/60
https://github.com/ibexa/docker/pull/11
https://github.com/ibexa/version-comparison/pull/52
https://github.com/ibexa/admin-ui/pull/726
https://github.com/ibexa/behat/pull/59
Tested in https://github.com/ibexa/commerce/pull/227
> [ibexa/docker] Upgraded Selenium version

- ibexa/commerce/4.5/config/routes/ibexa_order_management.yaml
> JIRA: - 
Restricted `ibexa/order-management` routes to admin siteaccesses.
> Restricted ibexa/order-management routes to admin siteaccesses

- ibexa/commerce/4.5/config/routes/ibexa_payment.yaml
- ibexa/commerce/4.5/manifest.json
- ibexa/payment/4.5/manifest.json
> JIRA: -
Added ibexa/payment package recipe.
> Added ibexa/payment package

- ibexa/commerce/4.5/assets/js/react.blocks.js
- ibexa/commerce/4.5/encore/package.json
- ibexa/commerce/4.5/encore/webpack.config.js
- ibexa/commerce/4.5/templates/themes/standard/full/welcome_page.html.twig
- ibexa/commerce/4.5/templates/themes/standard/pagelayout.html.twig
- ibexa/experience/4.5/assets/js/react.blocks.js
- ibexa/experience/4.5/encore/package.json
- ibexa/experience/4.5/encore/webpack.config.js
- ibexa/experience/4.5/templates/themes/standard/full/welcome_page.html.twig
- ibexa/experience/4.5/templates/themes/standard/pagelayout.html.twig
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-4962](https://issues.ibexa.co/browse/IBX-4962) |
| **Requires**                            | ibexa/corporate-account#154
| **Type**                                   | feature |
| **Target Ibexa version** | `v4.5` |
| **BC breaks**                          | no |
Implemented React app blocks configuration
> IBX-4962: React app blocks configuration

- ibexa/commerce/4.5/config/routes/ibexa_order_management.yaml
**Depends on https://github.com/ibexa/order-management/pull/27**
> IBX-4956: Added Orders REST API routing

- ibexa/commerce/4.5/config/routes/ibexa_corporate_account.yaml
- ibexa/experience/4.5/config/routes/ibexa_corporate_account.yaml
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-4170](https://issues.ibexa.co/browse/IBX-4170) |
| :warning:  **Requires**                            | ibexa/corporate-account#154
| **Type**                                   | feature |
| **Target Ibexa version** | `v4.5` |
| **BC breaks**                          | no |
To be merged with ibexa/corporate-account#154.
> [Fast forward] IBX-4170: Imported Corporate Account REST routing

- ibexa/cdp/4.5/config/packages/ibexa_cdp.yaml
> JIRA: https://issues.ibexa.co/browse/IBX-5586
> [ibexa/cdp] IBX-5586: Provided updated configuration format

- ibexa/commerce/4.5/assets/js/react.blocks.js
- ibexa/commerce/4.5/encore/ibexa.webpack.config.react.blocks.js
- ibexa/commerce/4.5/encore/webpack.config.js
- ibexa/commerce/4.5/templates/themes/standard/full/welcome_page.html.twig
- ibexa/commerce/4.5/templates/themes/standard/pagelayout.html.twig
- ibexa/experience/4.5/assets/js/react.blocks.js
- ibexa/experience/4.5/encore/ibexa.webpack.config.react.blocks.js
- ibexa/experience/4.5/encore/webpack.config.js
- ibexa/experience/4.5/templates/themes/standard/full/welcome_page.html.twig
- ibexa/experience/4.5/templates/themes/standard/pagelayout.html.twig
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-5543](https://issues.ibexa.co/browse/IBX-5543) |
| **Type**                                   | bug |
| **Target Ibexa version** | `v4.5` 
| **BC breaks**                          | no |
React Blocks fix error while creating bundle
React Blocks rendering in one file
> IBX-5543: React Blocks fix error while creating bundle

- ibexa/commerce/3.3/encore/webpack.config.js
- ibexa/commerce/4.4/encore/webpack.config.js
- ibexa/commerce/4.5/encore/webpack.config.js
- ibexa/commerce/4.6/encore/webpack.config.js
- ibexa/compatibility-layer/4.4/encore/webpack.config.js
- ibexa/compatibility-layer/4.5/encore/webpack.config.js
- ibexa/compatibility-layer/4.6/encore/webpack.config.js
- ibexa/content/3.3/encore/webpack.config.js
- ibexa/content/4.4/encore/webpack.config.js
- ibexa/content/4.5/encore/webpack.config.js
- ibexa/content/4.6/encore/webpack.config.js
- ibexa/experience/3.3/encore/webpack.config.js
- ibexa/experience/4.4/encore/webpack.config.js
- ibexa/experience/4.5/encore/webpack.config.js
- ibexa/experience/4.6/encore/webpack.config.js
- ibexa/oss/3.3/encore/webpack.config.js
- ibexa/oss/4.4/encore/webpack.config.js
- ibexa/oss/4.5/encore/webpack.config.js
- ibexa/oss/4.6/encore/webpack.config.js
Symfony is not adding this plugin in its config, so we should remove it as well.
> [All] Removed class properties plugin from babel

- ibexa/cdp/4.6/config/packages/ibexa_cdp.yaml
> JIRA: https://issues.ibexa.co/browse/IBX-5578
> Requires: https://github.com/ibexa/cdp/pull/14
> [ibexa/cdp] Added `cdp.data_export.content_data` configuration

- ibexa/commerce/4.5/config/packages/ibexa.yaml
- ibexa/commerce/4.5/config/packages/ibexa_admin_ui.yaml
- ibexa/commerce/4.6/config/packages/ibexa.yaml
- ibexa/commerce/4.6/config/packages/ibexa_admin_ui.yaml
JIRA: https://issues.ibexa.co/browse/IBX-6041
> IBX-6041: Fixed search list when filtering by creator name

- ibexa/cdp/4.6/config/packages/ibexa_cdp.yaml
> JIRA: https://issues.ibexa.co/browse/IBX-6606
Default configuration for: https://github.com/ibexa/cdp/pull/20
> IBX-6606: Added example configuration for CDP data export schedule

- ibexa/commerce/4.6/manifest.json
- ibexa/experience/4.6/manifest.json
- ibexa/headless/4.6/manifest.json
- ibexa/image-picker/4.6/manifest.json
JIRA: https://issues.ibexa.co/browse/IBX-7098
> IBX-7098: Added ibexa/image-picker package

- ibexa/commerce/4.6/encore/package.json
- ibexa/experience/4.6/encore/package.json
- ibexa/headless/4.6/encore/package.json
- ibexa/oss/4.6/encore/package.json
Requires:
https://github.com/ibexa/fieldtype-richtext/pull/136
https://github.com/ibexa/admin-ui-assets/pull/19
> [All] Upgraded CKE to version 40

- ibexa/commerce/4.6/config/packages/ibexa_site_context.yaml
- ibexa/experience/4.6/config/packages/ibexa_site_context.yaml
- ibexa/headless/4.6/config/packages/ibexa_site_context.yaml
> JIRA: https://issues.ibexa.co/browse/IBX-7242
Excluded "Product categories", "Tags" and "Corporate account" locations from site context.
> IBX-7242: Excluded "Product categories", "Tags" and "Corporate account" locations from site context

- ibexa/commerce/4.6/config/packages/ibexa_admin_ui.yaml
- ibexa/commerce/5.0/config/packages/ibexa_admin_ui.yaml
- ibexa/experience/4.6/config/packages/ibexa_admin_ui.yaml
- ibexa/experience/5.0/config/packages/ibexa_admin_ui.yaml
- ibexa/headless/4.6/config/packages/ibexa_admin_ui.yaml
- ibexa/headless/5.0/config/packages/ibexa_admin_ui.yaml
| :ticket: Issue | [IBX-7687](https://issues.ibexa.co/browse/IBX-7687) |
Add editor content icon to configuration above OSS
> IBX-7687: Add editor content icon to configuration above OSS

- ibexa/connector-openai/4.6/manifest.json
- ibexa/connector-openai/5.0/manifest.json
| :ticket: Issue | IBX-8618  |
Added recipe for `ibexa/connector-openai` package. So far this package doesn't require any configuration or routing import. 
`ibexa/connector-openai` package after installation should be configured correctly
This PR is part of the installation procedure.
> IBX-8618: Added recipe for ibexa/connector-openai package

- ibexa/dam-user/4.6/manifest.json
- ibexa/dam-user/5.0/manifest.json
| :ticket: Issue | [IBX-8557](https://issues.ibexa.co/browse/IBX-8557)|
> IBX-8557: Added ibexa/dam-user recipe

- ibexa/commerce/5.0/manifest.json
- ibexa/experience/5.0/manifest.json
- ibexa/headless/5.0/manifest.json
- ibexa/oss/5.0/manifest.json
> IBX-8137: [ibexa/*] Dropped Swiftmailer bundle

- ibexa/collaboration/4.6/manifest.json
- ibexa/collaboration/5.0/manifest.json
| :ticket: Issue | [IBX-8732](https://issues.ibexa.co/browse/IBX-8732) |
> IBX-8732: Added ibexa/collaboration recipe

- ibexa/connector-qualifio/4.6/config/routes/ibexa_qualifio.yaml
- ibexa/connector-qualifio/5.0/config/routes/ibexa_qualifio.yaml
| :ticket: Issue | IBX-8784 |
This PR adds new REST routes for Connector Qualifio.
> IBX-8784: Added ibexa/connector-qualifio REST routes

- ibexa/commerce/4.6/manifest.json
- ibexa/commerce/5.0/manifest.json
- ibexa/experience/4.6/manifest.json
- ibexa/experience/5.0/manifest.json
- ibexa/headless/4.6/manifest.json
- ibexa/headless/5.0/manifest.json
- ibexa/oss/4.6/manifest.json
- ibexa/oss/5.0/manifest.json
| :ticket: Issue | N/A |
The package was added to packagist https://packagist.org/packages/ibexa/core-search
> Enabled ibexa/core-search

- ibexa/discounts/4.6/config/routes/ibexa_discounts.yaml
- ibexa/discounts/4.6/manifest.json
- ibexa/discounts/5.0/config/routes/ibexa_discounts.yaml
- ibexa/discounts/5.0/manifest.json
| :ticket: Issue | IBX-XXXXX |
> Discounts base recipe

- ibexa/collaboration/4.6/manifest.json
- ibexa/collaboration/5.0/manifest.json
| :ticket: Issue | [IBX-8732](https://issues.ibexa.co/browse/IBX-8732) |
> IBX-8732: Fixed ibexa/collaboration recipe

- ibexa/commerce/5.0/encore/package.json
- ibexa/experience/5.0/encore/package.json
- ibexa/headless/5.0/encore/package.json
- ibexa/oss/5.0/encore/package.json
| :ticket: Issue | IBX-9419 |
- https://github.com/ibexa/ts-config-ibexa/pull/2
> IBX-9419: Updated ts-config tag

- ibexa/commerce/4.6/config/packages/ibexa.yaml
- ibexa/commerce/5.0/config/packages/ibexa.yaml
| :ticket: Issue | IBX-8552 |
- https://github.com/ibexa/user/pull/98
- https://github.com/ibexa/checkout/pull/213
- https://github.com/ibexa/storefront/pull/200
> IBX-8552: Changed customer registration group id to remote id

- ibexa/test-fixtures/4.6/manifest.json
- ibexa/test-fixtures/5.0/manifest.json
| :ticket: Issue | IBX-6236 |
- https://github.com/ibexa/test-fixtures/pull/74
> IBX-6236 Added config files for custom tags and custom styles

- ibexa/commerce/5.0/config/packages/csrf.yaml
- ibexa/commerce/5.0/config/packages/ibexa_oauth2_server.yaml
- ibexa/commerce/5.0/encore/webpack.config.js
- ibexa/experience/5.0/config/packages/csrf.yaml
- ibexa/experience/5.0/config/packages/ibexa_oauth2_server.yaml
- ibexa/experience/5.0/encore/webpack.config.js
- ibexa/headless/5.0/config/packages/csrf.yaml
- ibexa/headless/5.0/config/packages/ibexa_oauth2_server.yaml
- ibexa/headless/5.0/encore/webpack.config.js
- ibexa/oss/5.0/config/packages/csrf.yaml
- ibexa/oss/5.0/encore/webpack.config.js
| :ticket: Issue | IBX-8471 |
Prepared recipes for Symfony 7
Regressions
Upgrade documentation
> IBX-8471: Upgraded codebase to Symfony 7

- ibexa/rector/5.0/manifest.json
- ibexa/rector/5.0/rector.config.js
| :ticket: Issue | [IBX-8365](https://issues.ibexa.co/browse/IBX-8365) |
> IBX-8365: [ibexa/rector] Added rector.config.js

- ibexa/commerce/4.6/config/packages/ibexa_twig_components.yaml
- ibexa/commerce/5.0/config/packages/ibexa_twig_components.yaml
- ibexa/experience/4.6/config/packages/ibexa_twig_components.yaml
- ibexa/experience/5.0/config/packages/ibexa_twig_components.yaml
- ibexa/headless/4.6/config/packages/ibexa_twig_components.yaml
- ibexa/headless/5.0/config/packages/ibexa_twig_components.yaml
- ibexa/oss/4.6/config/packages/ibexa_twig_components.yaml
- ibexa/oss/5.0/config/packages/ibexa_twig_components.yaml
- ibexa/twig-components/4.6/manifest.json
- ibexa/twig-components/5.0/manifest.json
| :ticket: Issue | IBX-9697 |
Added recipe for ibexa/twig-components
> IBX-9697: Added recipe for ibexa/twig-components

- ibexa/commerce/5.0/config/packages/mailer.yaml
- ibexa/experience/5.0/config/packages/mailer.yaml
- ibexa/headless/5.0/config/packages/mailer.yaml
- ibexa/oss/5.0/config/packages/mailer.yaml
| :ticket: Issue | IBX-9353 |
We either have to pass sender in every Email Notification Object (which in some cases is taken from email tempalte block) or configure it globally on mailer level.
> IBX-9353: Added default mailer configuration with global sender

- ibexa/commerce/4.6/manifest.json
- ibexa/commerce/5.0/manifest.json
- ibexa/experience/4.6/manifest.json
- ibexa/experience/5.0/manifest.json
- ibexa/headless/4.6/manifest.json
- ibexa/headless/5.0/manifest.json
- ibexa/oss/4.6/manifest.json
- ibexa/oss/5.0/manifest.json
| :ticket: Issue | IBX-9697 |
Added Ibexa Twig Components bundle to manifest
> IBX-9697: Added Ibexa Twig Components bundle to manifest

- ibexa/share/4.6/config/routes/ibexa_share.yaml
- ibexa/share/5.0/config/routes/ibexa_share.yaml
| :ticket: Issue | [IBX-10299](https://issues.ibexa.co/browse/IBX-10299) |
- https://github.com/ibexa/admin-ui/pull/1631
- https://github.com/ibexa/share/pull/93
> IBX-10299: [ibexa/share] Added routing config 

- ibexa/commerce/5.0/encore/custom.tsconfig.mjs
- ibexa/commerce/5.0/manifest.json
- ibexa/experience/5.0/encore/custom.tsconfig.mjs
- ibexa/experience/5.0/manifest.json
- ibexa/headless/5.0/encore/custom.tsconfig.mjs
- ibexa/headless/5.0/manifest.json
- ibexa/oss/5.0/encore/custom.tsconfig.mjs
- ibexa/oss/5.0/manifest.json
| :ticket: Issue | IBX-10317 |
> IBX-10317: Remove unnecessary custom.tsconfig.mjs file

- ibexa/commerce/5.0/encore/package.json
- ibexa/experience/5.0/encore/package.json
- ibexa/headless/5.0/encore/package.json
- ibexa/oss/5.0/encore/package.json
| :ticket: Issue | IBX-10340 |
> IBX-10340: Updated frontend-config version in package.json

- ibexa/commerce/5.0/config/packages/ibexa_solr.yaml
- ibexa/experience/5.0/config/packages/ibexa_solr.yaml
- ibexa/headless/5.0/config/packages/ibexa_solr.yaml
- ibexa/oss/5.0/config/packages/ibexa_solr.yaml
| :ticket: Issue | IBX-10231 |
|----------------|--|
Removed Solr parameters from configuration file
> IBX-10231: Removed Solr parameters from configuration file

- ibexa/commerce/4.6/encore/package.json
- ibexa/experience/4.6/encore/package.json
- ibexa/headless/4.6/encore/package.json
- ibexa/oss/4.6/encore/package.json
| :ticket: Issue | IBX-10261 |
> IBX-10261: Enabled special characters plugin in CKE

- ibexa/commerce/5.0/manifest.json
- ibexa/experience/5.0/manifest.json
- ibexa/headless/5.0/manifest.json
- ibexa/oss/5.0/manifest.json
| :ticket: Issue | IBX-XXXXX |
> Fixed TSConfig relative paths flag

- ibexa/commerce/5.0/encore/webpack.config.js
- ibexa/experience/5.0/encore/webpack.config.js
- ibexa/headless/5.0/encore/webpack.config.js
- ibexa/oss/5.0/encore/webpack.config.js
| :ticket: Issue | IBX-XXXXX |
#200 introduced the wrong indent.
The line starting with `.` from line 12 to 27 are linked to the Encore object line 11, that's why they are indent this way.
The line below are not related to this object and shouldn't pretended to be part of the same function chain.
I removed the confusing tabs.
> Fix webpack.config.js indent

- ibexa/commerce/4.6/config/packages/mailer.yaml
- ibexa/experience/4.6/config/packages/mailer.yaml
- ibexa/headless/4.6/config/packages/mailer.yaml
- ibexa/oss/4.6/config/packages/mailer.yaml
| :ticket: Issue | IBX-9353 |
Backported https://github.com/ibexa/recipes-dev/pull/190 to 4.6. 
N/A
N/A
> IBX-9353: Added default mailer configuration with global sender (4.6)

- ibexa/commerce/4.6/config/packages/security.yaml
- ibexa/experience/4.6/config/packages/security.yaml
- ibexa/headless/4.6/config/packages/security.yaml
| :ticket: Issue | [IBX-10525](https://issues.ibexa.co/browse/IBX-10525) |
> IBX-10525: Added shareable_link firewall

- ibexa/commerce/4.6/config/packages/security.yaml
- ibexa/commerce/5.0/config/packages/security.yaml
- ibexa/experience/4.6/config/packages/security.yaml
- ibexa/experience/5.0/config/packages/security.yaml
- ibexa/headless/4.6/config/packages/security.yaml
- ibexa/headless/5.0/config/packages/security.yaml
| :ticket: Issue | [IBX-10525 ](https://issues.ibexa.co/browse/IBX-10525)|
- https://github.com/ibexa/collaboration/pull/91 (4.6)
> IBX-10525: Added shareable link firewall for 5.x
