ibexa/recipes-dev

- .github/workflows/bot.yaml
- .github/workflows/ci.yaml
- .github/workflows/flex-cleanup.yaml
- ibexa/commerce/3.3/config/packages/ezplatform_solr.yaml
- ibexa/commerce/4.0/config/packages/ibexa_solr.yaml
- ibexa/commerce/4.1/config/packages/ibexa_solr.yaml
This PR introduces basic CI for our recipes. It's based on the Symfony workflows, but modified and simplified a bit.
There are three workflows:
1) CI: 
- generates a test endpoint so that changes can be tested before merging. Based on https://github.com/symfony/recipes/blob/main/.github/workflows/callable-qa.yml , but simplified - but we can expand it in the future if we want 😄 
Symfony generates a test endpoint with recipes only for packages that have been changed - I don't think it works in our case, as we would have to use a fallback endpoint all the time for the recipes that are missing in the test endpoint, which seems error-prone.
2) Cleanup:
- based on https://github.com/symfony/recipes/blob/main/.github/workflows/callable-flex-cleanup.yml
- removes the test endpoint branch …
> [CI] Added basic CI for recipes

- ibexa/commerce/4.2/config/packages/security.yaml
- ibexa/content/4.2/config/packages/security.yaml
- ibexa/experience/4.2/config/packages/security.yaml
- ibexa/oss/4.2/config/packages/security.yaml
As this endpoint must be accessible even without `user/register` policy.
> [ibexa/*] Excluded register from invitation endpoint from main firewall

- ibexa/docker/3.3/manifest.json
- ibexa/docker/4.1/manifest.json
- ibexa/docker/4.2/manifest.json
We are changing the versioning approach in the `ibexa/docker` package to make things consistent and avoid confusion.
- the versions 0.1 and 0.2 will no longer be developed
- version 0.1.x will become 3.3.x
- version 0.2.x will be split so that there's a corresponding branch for every DXP version: 4.1.x, 4.2.x, 4.3.x etc.
I'm keeping the old recipes for BC (so that the old tags still work as they used to).
> [ibexa/docker] Added recipes for new branches in Docker package

- ibexa/commerce/3.3/config/packages/ezplatform.yaml
- ibexa/commerce/3.3/config/packages/ezplatform_admin_ui.yaml
- ibexa/commerce/4.2/config/packages/ibexa.yaml
- ibexa/commerce/4.2/config/packages/ibexa_admin_ui.yaml
- ibexa/content/3.3/config/packages/ezplatform.yaml
- ibexa/content/3.3/config/packages/ezplatform_admin_ui.yaml
- ibexa/content/4.2/config/packages/ibexa.yaml
- ibexa/content/4.2/config/packages/ibexa_admin_ui.yaml
- ibexa/experience/3.3/config/packages/ezplatform.yaml
- ibexa/experience/3.3/config/packages/ezplatform_admin_ui.yaml
- ibexa/experience/4.2/config/packages/ibexa.yaml
- ibexa/experience/4.2/config/packages/ibexa_admin_ui.yaml
> JIRA: https://issues.ibexa.co/browse/IBX-3782
@ibexa/quality-assurance found during testing that our configuration for AdminUI is kept in two config files which leads to various issues when you make changes to one file only.
> IBX-3782: Moved AdminUI related configuration to ibexa_admin_ui.yaml

- ibexa/commerce/4.3/config/packages/ibexa.yaml
- ibexa/commerce/4.4/config/packages/ibexa.yaml
Related to:
https://github.com/ibexa/commerce-shop/pull/108
As mentioned in:
https://github.com/ibexa/recipes-dev/pull/28#issuecomment-1293271636
`customer` content type is only part of commerce edition, hence it make sense to configure it only on that level instead of package as `commerce-shop` is available in content edition upwards.
> [ibexa/commerce] Added register configuration

- ibexa/commerce/4.4/config/packages/ibexa_solr.yaml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | IBX-3815
| **Type**                                   | feature
| **Target Ibexa version** | `v4.4`
| **BC breaks**                          | no
| **Doc needed**                       | yes
Aligned ibexa_solr.yaml with ibexa/experience and ibexa/content recipes as we no longer use Solarium Bundle
> IBX-3815: Removed Solarium Bundle compatibility

- ibexa/commerce/4.4/config/packages/ibexa.yaml
- ibexa/commerce/4.4/manifest.json
- ibexa/content/4.4/config/packages/ibexa.yaml
- ibexa/content/4.4/manifest.json
- ibexa/experience/4.4/config/packages/ibexa.yaml
- ibexa/experience/4.4/manifest.json
Ref: https://github.com/ibexa/core/pull/194
Without exposing it to env variable, local environment would be handicapped to use the same configuration as ie. Platform.sh does (and Fastly IO does not work on local environment).
> IBX-3767: Exposed default image variation handler as env variable

- ibexa/commerce/3.3/config/packages/ezplatform_admin_ui.yaml
- ibexa/commerce/4.3/config/packages/ibexa_admin_ui.yaml
- ibexa/commerce/4.4/config/packages/ibexa_admin_ui.yaml
- ibexa/content/3.3/config/packages/ezplatform_admin_ui.yaml
- ibexa/content/4.3/config/packages/ibexa_admin_ui.yaml
- ibexa/content/4.4/config/packages/ibexa_admin_ui.yaml
- ibexa/experience/3.3/config/packages/ezplatform_admin_ui.yaml
- ibexa/experience/4.3/config/packages/ibexa_admin_ui.yaml
- ibexa/experience/4.4/config/packages/ibexa_admin_ui.yaml
- ibexa/oss/3.3/config/packages/ezplatform_admin_ui.yaml
- ibexa/oss/4.3/config/packages/ibexa_admin_ui.yaml
- ibexa/oss/4.4/config/packages/ibexa_admin_ui.yaml
> Added missing comment about crucial default `eng-GB` language under `admin_group`

- ibexa/commerce/4.5/manifest.json
Fix for the namespace wrongly added in https://github.com/ibexa/recipes-dev/pull/58.
> [ibexa/commerce] Fixed `IbexaOrderManagementBundle` namespace

- ibexa/commerce/4.6/config/routes/ibexa_shipping.yaml
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-5710](https://issues.ibexa.co/browse/IBX-5710) |
| **Requires**                           | https://github.com/ibexa/shipping/pull/24
| **Type**                                   | feature |
| **Target Ibexa version** | `v4.6` |
| **BC breaks**                          | no |
This PR configures routing for ibexa/shipping REST endpoints.
Given the first PR introducing resource referenced here has been merged, this is also ready for merging when needed.
> IBX-5710: [ibexa/commerce] Configured `ibexa/shipping` REST routing

- ibexa/test-fixtures/4.6/manifest.json
JIRA: https://issues.ibexa.co/browse/IBX-6324
This PR leverages the new `add-lines` configurator to specify configuration based on installed project edition - this means that only some of the files will be enabled when the bundle is installed. 
Moving the configuration part to recipes makes sure that cache is cleared after the package is added, solving a whole range of issues for us.
Requires: https://github.com/ibexa/test-fixtures/pull/45 for the configuration files
Result:
And the configuration files are copied from test-fixtures directly.
Doc:
https://github.com/symfony/flex/pull/975
https://github.com/symfony/recipes/blob/544ff21cd02720ce5fa7f2276aa577aaf87eda0b/README.rst#add-lines-configurator
> Added Test Fixtures recipes

- ibexa/commerce/4.6/config/packages/payum.yaml
As configuration file is added from payum recipes, it duplicates (and throws exception) ours from payum-connector.
I have dropped configuration here https://github.com/ibexa/connector-payum/pull/1/commits/62b8d08e0100582c00c601db5adf37e1dcaa7d91 and moved everything at application level.
> [commerce] Moved Payum configuration from bundle

- ibexa/commerce/4.6/config/packages/ibexa_admin_ui.yaml
- ibexa/experience/4.6/config/packages/ibexa_admin_ui.yaml
- ibexa/headless/4.6/config/packages/ibexa_admin_ui.yaml
> JIRA: https://issues.ibexa.co/browse/IBX-6645
Enabled and configured user profile for headless/exp/commerce editions
> IBX-6645: Implemented user profile

- ibexa/test-fixtures/4.5/manifest.json
Same as https://github.com/ibexa/recipes-dev/pull/85 , but for 4.5 - it makes no sense to have the configuration in two different formats, it makes upmerges a nightmare.
The only change: `headless` is changed to `content` everywhere.
Requires: https://github.com/ibexa/test-fixtures/pull/54
> [ibexa/test-fixtures] Added configuration recipe for 4.5

- ibexa/test-fixtures/4.5/manifest.json
- ibexa/test-fixtures/4.6/manifest.json
Required for https://github.com/ibexa/test-fixtures/pull/55
https://github.com/ibexa/test-fixtures/pull/55 uncovered a unpleaseant behaviour in the current configuration setup:
Symfony loads the YAML configuration files in "random"* order, meaning that the two configurations:
- ibexa_site_factory.yaml sets the `enabled` value to `false`
- experience.yaml sets the `enabled` value to `true`
are loaded and merged together - and the Site Factory one is loaded later.
Running:
` php bin/console debug:config ibexa_site_factory` returns:
```
ibexa_site_factory:
enabled: false
update_roles:
- Anonymous
- Administrator
templates:
site_template:
siteaccess_group: site_factory_group
name: 'Example Site'
thumbnail: /bundles/ibexasitefactory/img/template-placeholder.png
site_skeleton_id: null …
```
> [ibexa/test-fixtures] Moved configuration import to services.yaml

- ibexa/commerce/4.6/encore/package.json
- ibexa/experience/4.6/encore/package.json
- ibexa/headless/4.6/encore/package.json
- ibexa/oss/4.6/encore/package.json
Jira ref: https://issues.ibexa.co/browse/IBX-7525
Added svgr for wepack, is need for support svg file in react
> IBX-7525: UDW as npm package

- ibexa/docker/4.6/manifest.json
Suggested by https://github.com/ibexa/docker/issues/30
> [ibexa/docker] Set the default image to php:8.2-node18

- ibexa/commerce/4.5/config/packages/ibexa_elasticsearch.yaml
- ibexa/commerce/4.6/config/packages/ibexa_elasticsearch.yaml
- ibexa/commerce/5.0/config/packages/ibexa_elasticsearch.yaml
- ibexa/content/4.5/config/packages/ibexa_elasticsearch.yaml
- ibexa/experience/4.5/config/packages/ibexa_elasticsearch.yaml
- ibexa/experience/4.6/config/packages/ibexa_elasticsearch.yaml
- ibexa/experience/5.0/config/packages/ibexa_elasticsearch.yaml
- ibexa/headless/4.6/config/packages/ibexa_elasticsearch.yaml
- ibexa/headless/5.0/config/packages/ibexa_elasticsearch.yaml
JIRA: https://issues.ibexa.co/browse/IBX-3740
For quite some time, Platform.sh relies on `ELASTICSEARCH_URL` env variable, ref:
https://github.com/platformsh/symfonyflex-bridge/blob/b30d3309a02f770e5aec8db06ce59972253a9d0a/platformsh-flex-env.php#L306. Added fallbacking from `ELASTICSEARCH_DSN` to `ELASTICSEARCH_URL` seems to do the trick and saves developers from necessity to set any additional env variables on their Platform.sh instances.
**Note:**
Performing:
```
1. bin/console ibexa:elasticsearch:put-index-template --overwrite
2. curl -X DELETE 'http://elasticsearch.internal:9200/_all'
3. bin/console ibexa:reindex
```
once, might be necessary for the new configuration to be picked up.
> IBX-3740: Fixed resolving `ELASTICSEARCH_DSN` variable for Platform.sh

- ibexa/rector/5.0/manifest.json
- ibexa/rector/5.0/rector.php
| :ticket: Issue | IBX-8117 |
- https://github.com/ibexa/rector/pull/1
This is default ibexa/rector config file (`./rector.php`) to be installed when installing ibexa/rector package.
Optionally, confirm that this recipe gets installed when requiring `ibexa/rector`.
Possibly needs to be mentioned when documenting rector that this is expected to happen (if we decide to document this outside of the package README).
> IBX-8117: [ibexa/rector] Added default configuration for ibexa/rector

- ibexa/commerce/5.0/encore/ibexa.webpack.config.manager.js
- ibexa/commerce/5.0/encore/webpack.config.js
- ibexa/experience/5.0/encore/ibexa.webpack.config.manager.js
- ibexa/experience/5.0/encore/webpack.config.js
- ibexa/headless/5.0/encore/ibexa.webpack.config.manager.js
- ibexa/headless/5.0/encore/webpack.config.js
- ibexa/oss/5.0/encore/ibexa.webpack.config.manager.js
- ibexa/oss/5.0/encore/webpack.config.js
| :ticket: Issue | [IBX-8144](https://issues.ibexa.co/browse/IBX-8144) |
Sonar is not able to be green, as these changes are similar between all four editions, so it will be always treated as duplicated code...
> IBX-8144: [Rebranding] Remove compatibility layer from webpack encore

- ibexa/commerce/5.0/config/packages/security.yaml
- ibexa/experience/5.0/config/packages/security.yaml
- ibexa/headless/5.0/config/packages/security.yaml
- ibexa/oss/5.0/config/packages/security.yaml
| :ticket: Issue | IBX-8140 |
This PR is about switching to the new authorization mechanism that was introduced as part of Symfony 5.4 release. The main trigger allowing us to rely on the new mechanism from now on is setting `enable_authenticator_manager: true`. All the related PRs adapt the existing codebase and base functionalities like login/logout/redirect to work with the new setup.
**The most important part is not having a token for anonymous users which forces us to revisit the approach to such users. In practice we need to deal with `null` value instead of token for anonymous users.**
- https://github.com/ibexa/core/pull/368
- https://github.com/ibexa/rest/pull/90
- https://github.com/ibexa/admin-ui/pull/1264
We should mention that those changes are …
> IBX-8140: Enabled authenticator manager-based security

- ibexa/commerce/5.0/config/packages/security.yaml
- ibexa/experience/5.0/config/packages/security.yaml
- ibexa/headless/5.0/config/packages/security.yaml
- ibexa/oss/5.0/config/packages/security.yaml
| :ticket: Issue | IBX-8356 |
- https://github.com/ibexa/core/pull/375 (will be merged at the end, not blocking this part)
- https://github.com/ibexa/rest/pull/101
This PR is about making JWT authentication compliant with the Symfony security changes (and bringing it back in the first place 😅). The main source of truth that was used is https://symfony.com/bundles/LexikJWTAuthenticationBundle/current/index.html#symfony-5-3-and-higher.
Additionally, I used
```
username_path: JWTInput.username
password_path: JWTInput.password
```
to make the request payload BC safe (username and password are taken from specific keys from the payload so no changes are needed on consumer's end).
If we mention security configuration changes anywhere, we need to include changes …
> IBX-8356: Reworked JWT firewall to be in-tact with the new Symfony auth

- ibexa/commerce/5.0/config/packages/ibexa.yaml
- ibexa/experience/5.0/config/packages/ibexa.yaml
- ibexa/headless/5.0/config/packages/ibexa.yaml
- ibexa/oss/5.0/config/packages/ibexa.yaml
| :ticket: Issue | IBX-8137 |
https://github.com/ibexa/user/pull/84
> [ibexa/*] Added symfony/notifier subscriptions

- ibexa/rector/5.0/rector.php
> [!CAUTION]
> Requires ibexa/rector#6 to be merged first
| :ticket: Issue | IBX-8394 |
- https://github.com/ibexa/rector/pull/6
Changed default configuration recipe to include changes from ibexa/rector#6 - instead of hardcoding path to `./vendor/ibexa/rector/src/contracts/Sets/ibexa-50.php`, an `enum IbexaSetList` has been introduced and used.
I've also aligned the config file with the format showcased ATM by https://getrector.com/documentation.
> IBX-8394: [ibexa/rector] Improved default configuration

- ibexa/commerce/5.0/config/packages/ibexa_page_builder.yaml
- ibexa/commerce/5.0/config/packages/security.yaml
- ibexa/experience/5.0/config/packages/ibexa_page_builder.yaml
- ibexa/experience/5.0/config/packages/security.yaml
| :ticket: Issue | IBX-8324 |
- https://github.com/ibexa/page-builder/pull/388
`Symfony\Component\Security\Core\Authentication\Provider\AnonymousAuthenticationProvider` was doing the job before it got deprecated. It means all the `/_fragment` calls were caught and `PermissionResolver::setCurrentUserPreference` was invoked so we were authenticated. Since we cannot rely on this mechanism anymore, I needed to figure out how to make sure we won't be having unauthenticated calls in page builder resulting in login screen redirection.
It just won't work - each call needs to go through built-in Symfony authenticator-based system whereas authentication providers are not to be relied upon anymore. Besides, we don't have any security-related events that are available …
> IBX-8324: Reworked JWT editorial bearer in page builder

- ibexa/commerce/5.0/config/packages/security.yaml
- ibexa/experience/5.0/config/packages/security.yaml
- ibexa/headless/5.0/config/packages/security.yaml
| :ticket: Issue | IBX-8656 |
- https://github.com/ibexa/oauth2-client/pull/31
- https://github.com/ibexa/core/pull/411
Changes in the OAuth2 client firewall configuration are mostly a natural consequence of:
```
security:
enable_authenticator_manager: true 
```
which we enabled in the beginning. Related PRs explain in more details how the deprecated guard authenticator-based security was redone.
> IBX-8656: Reworked OAuth2 client authentication to comply with new Symfony security

- ibexa/commerce/5.0/config/packages/security.yaml
- ibexa/experience/5.0/config/packages/security.yaml
- ibexa/headless/5.0/config/packages/security.yaml
| :ticket: Issue | IBX-8657 |
- https://github.com/ibexa/cdp/pull/27
This time changes are pretty simple - we only replace deprecated `guard` configuration key with our own, adjusted CDP authenticator implementation.
The whole flow related to integration with CDP needs to be verified.
Config change.
> IBX-8657: Reworked CDP security layer to not rely on deprecated guard authenticators

- ibexa/commerce/5.0/config/packages/security.yaml
- ibexa/experience/5.0/config/packages/security.yaml
- ibexa/headless/5.0/config/packages/security.yaml
- ibexa/oss/5.0/config/packages/security.yaml
| :ticket: Issue | IBX-8817 |
This PR aims to document how `http_basic` authenticator can be used. All the necessary documentation that needs to be put in place can be found here https://symfony.com/doc/5.x/security.html#http-basic.
The example `ibexa_http_basic` firewall allows authorizing via browser window whenever inaccessible resource is reached by just passing regular user data.
From the technical point of view, all the work is done by built-in Symfony `Symfony\Component\Security\Http\Authenticator\HttpBasicAuthenticator`.
To properly check proposed changes one needs to uncomment `ibexa_http_basic` firewall and enter any URL that shouldn't be visible without being logged in using regular credentials (e.g. `/admin/dashboard`). After populating the …
> IBX-8817: Documented `http_basic` authentication config

- ibexa/product-catalog-symbol-attribute/4.6/config/ibexa_product_catalog_symbol_attribute.yaml
- ibexa/product-catalog-symbol-attribute/4.6/manifest.json
- ibexa/product-catalog-symbol-attribute/5.0/config/ibexa_product_catalog_symbol_attribute.yaml
- ibexa/product-catalog-symbol-attribute/5.0/manifest.json
| :ticket: Issue | IBX-8775 |
Added recipe for `ibexa/product-catalog-symbol-attribute` package
`ibexa/product-catalog-symbol-attribute` package after installation should be configured correctly
This PR is part of the `ibexa/product-catalog-symbol-attribute` package documentation.
> IBX-8775: Added recipe for ibexa/product-catalog-symbol-attribute

- ibexa/core-search/4.6/manifest.json
- ibexa/core-search/5.0/manifest.json
> Added recipe for ibexa/core-search

- ibexa/product-catalog-symbol-attribute/4.6/manifest.json
- ibexa/product-catalog-symbol-attribute/5.0/manifest.json
If you look at other packages then the `::class` suffix is not used:
https://github.com/ibexa/recipes-dev/blob/master/ibexa/connector-ai/4.6/manifest.json#L4
The current one results in Flex actually adding:
```
Ibexa\Bundle\ProductCatalogSymbolAttribute\IbexaProductCatalogSymbolAttributeBundle::class::class => ['all' => true],
```
and then failing
> [ibexa/product-catalog-symbol-attribute] Fixed the bundle entry

- ibexa/commerce/5.0/manifest.json
- ibexa/experience/5.0/manifest.json
- ibexa/headless/5.0/manifest.json
- ibexa/oss/5.0/manifest.json
> [!CAUTION]
> This is a part of bigger set of changes, to be merged together when ready
> - [x] :exclamation:  **Remove TMP commits before merge** :exclamation:
| :ticket: Issue | IBX-8470  |
This PR bumps Symfony to v6 with codebase upgrades.
Key changes:
Sanities in the form of regression tests.
No documentation required.
> IBX-8470: Upgraded codebase to Symfony 6

- ibexa/test-fixtures/4.5/manifest.json
- ibexa/test-fixtures/4.6/manifest.json
- ibexa/test-fixtures/5.0/manifest.json
| :ticket: Issue | n/a |
|----------------|-----|
- https://github.com/ibexa/test-fixtures/pull/70
- https://github.com/ibexa/recipes-dev/pull/85
- https://github.com/ibexa/recipes-dev/pull/102
Current recipes produce `config/services.yaml` as follows:
```yaml
imports:
- { resource: packages/test_fixtures/commerce.yaml }:
- { resource: packages/test_fixtures/experience.yaml }:
- { resource: packages/test_fixtures/headless.yaml }:
```
That trailing colon causes [a fatal error](https://github.com/ibexa/test-fixtures/actions/runs/13416547742/job/37478660627?pr=70#step:10:2264) when clearing Symfony cache.
Install test-fixtures to observe the issue.
> [ibexa/test-fixtures] Fixed configuration recipes

- .github/workflows/ci.yaml
- .github/workflows/flex-cleanup.yaml
| :ticket: Issue | n/a |
|----------------|-----|
Ubuntu 20.04 for GHA is in a process of being discontinued.
See the failure on upstream recipes blocking the release process now: https://github.com/ibexa/recipes/actions/runs/13656723063
Updated to `ubuntu-latest` to avoid maintenance cost in the future. Let's see if CI agrees.
> [GHA] Bumped Ubuntu to ubuntu-latest in all workflows

- ibexa/rector/4.6/manifest.json
- ibexa/rector/4.6/rector.php
| :ticket: Issue | n/a |
This PR backports `5.0` configuration to `4.6`. `4.6` branch is already available for `ibexa/rector` package.
Ibexa 5.0 set contains deprecations that should be removed in 4.6 anyway.
There might be some minor differences (like we deprecated something in 5.0 only). We could approach that in several ways:
* ~Keep different contents of `5.0` set list between `4.6` and `5.0` branches in `ibexa/rector` package,~
* Keep a copy of the `5.0` set as the `4.6` set with changes, :heavy_check_mark: chosen solution
* ~Ensure all `5.0` rules are executable on `4.6`.~
**Update Jan 28:** after today's dry run for the presentation the conclusion was that having `IBEXA_46` set would look less confusing in case of 4.6.
**Update Mar 12:** changed PR to …
> [ibexa/rector] Backported Ibexa Rector recipe to 4.6

- ibexa/commerce/5.0/config/packages/ibexa.yaml
- ibexa/commerce/5.0/config/packages/security.yaml
- ibexa/experience/5.0/config/packages/ibexa.yaml
- ibexa/experience/5.0/config/packages/security.yaml
- ibexa/headless/5.0/config/packages/ibexa.yaml
- ibexa/headless/5.0/config/packages/security.yaml
- ibexa/oss/5.0/config/packages/ibexa.yaml
- ibexa/oss/5.0/config/packages/security.yaml
| :ticket: Issue | IBX-9584  |
Manually fixed deprecation warning for Symfony 6.x:
* Replaced deprecated "enable_annotations" option at "framework.validation" with "enable_attributes"  
* Removed deprecated "enable_authenticator_manager" option from security configuration
* Removed deprecated "require_previous_session" option from security.firewalls.ibexa_front.form_login configuration 
Sanities.
N/A
> IBX-9584: Resolved Symfony 6.x deprecations vol. 2

- ibexa/discounts-codes/4.6/config/routes/ibexa_discounts_codes.yaml
| :ticket: Issue | - |
Followup for https://github.com/ibexa/recipes-dev/pull/162 where the issue emerges only on `4.6`.
> Fixed wrong REST endpoints path for `4.6`

- ibexa/fieldtype-richtext-rte/4.6/config/packages/ibexa_fieldtype_richtext_rte.yaml
- ibexa/fieldtype-richtext-rte/4.6/config/routes/ibexa_fieldtype_richtext_rte.yaml
- ibexa/fieldtype-richtext-rte/4.6/manifest.json
- ibexa/fieldtype-richtext-rte/5.0/config/packages/ibexa_fieldtype_richtext_rte.yaml
- ibexa/fieldtype-richtext-rte/5.0/config/routes/ibexa_fieldtype_richtext_rte.yaml
- ibexa/fieldtype-richtext-rte/5.0/manifest.json
| :ticket: Issue | IBX-9339 |
- https://github.com/ibexa/fieldtype-richtext-rte/pull/10
Added recipe for `ibexa/fieldtype-richtext-rte` package
`ibexa/fieldtype-richtext-rte` package should be installed correctly. 
N/A
> IBX-9339: Added recipe for ibexa/fieldtype-richtext-rte

- ibexa/commerce/5.0/config/packages/ibexa_assets.yaml
- ibexa/commerce/5.0/encore/ibexa.webpack.config.js
- ibexa/commerce/5.0/encore/package.json
- ibexa/experience/5.0/config/packages/ibexa_assets.yaml
- ibexa/experience/5.0/encore/ibexa.webpack.config.js
- ibexa/experience/5.0/encore/package.json
- ibexa/headless/5.0/config/packages/ibexa_assets.yaml
- ibexa/headless/5.0/encore/ibexa.webpack.config.js
- ibexa/headless/5.0/encore/package.json
- ibexa/oss/5.0/config/packages/ibexa_assets.yaml
- ibexa/oss/5.0/encore/ibexa.webpack.config.js
- ibexa/oss/5.0/encore/package.json
| :ticket: Issue | IBX-9916 |
From now on, it is crucial to use `yarn encore prod` or have `NODE_ENV` set to `production` on the production environment. Using `yarn encore dev` will cause React to load in development version, which is not ideal in a production environment. 
We probably like to have some disclaimer in the upgrade doc for 5.0. // cc @mnocon
> IBX-9916: Upgrade frontend dependencies

- ibexa/commerce/5.0/encore/custom.tsconfig.mjs
- ibexa/commerce/5.0/encore/ibexa.tsconfig.json
- ibexa/commerce/5.0/encore/ibexa.webpack.config.js
- ibexa/commerce/5.0/encore/package.json
- ibexa/commerce/5.0/manifest.json
- ibexa/experience/5.0/encore/custom.tsconfig.mjs
- ibexa/experience/5.0/encore/ibexa.tsconfig.json
- ibexa/experience/5.0/encore/ibexa.webpack.config.js
- ibexa/experience/5.0/encore/package.json
- ibexa/experience/5.0/manifest.json
- ibexa/headless/5.0/encore/custom.tsconfig.mjs
- ibexa/headless/5.0/encore/ibexa.tsconfig.json
- ibexa/headless/5.0/encore/ibexa.webpack.config.js
- ibexa/headless/5.0/encore/package.json
- ibexa/headless/5.0/manifest.json
- ibexa/oss/5.0/encore/custom.tsconfig.mjs
- ibexa/oss/5.0/encore/ibexa.tsconfig.json
- ibexa/oss/5.0/encore/ibexa.webpack.config.js
- ibexa/oss/5.0/encore/package.json
- ibexa/oss/5.0/manifest.json
| :ticket: Issue | IBX-9939 |
In all `package.json` there's only `"fork-ts-checker-webpack-plugin": "^7.0.0",` added, rest changes is just sorted of dependencies.
And `@ibexa/ts-config` package was updated to v1.1
I've changed approach of generating aliases to handle case of using addons which adds their own addons. Now tsconfig.json is generating automatically with post-update-cmd and if developer wants to overwrite our config from ibexa.tsconfig.json he can use file `custom.tsconfig.mjs` to overwrite specific parts of it.
> IBX-9939: TypeScript aliases for bundles

- ibexa/commerce/5.0/config/packages/ibexa_admin_ui.yaml
- ibexa/experience/5.0/config/packages/ibexa_admin_ui.yaml
- ibexa/headless/5.0/config/packages/ibexa_admin_ui.yaml
- ibexa/oss/5.0/config/packages/ibexa_admin_ui.yaml
| :ticket: Issue | IBX-10139 |
As of 5.0 we will have one icon set, so we do not need to override content types icons from admin-ui to change them to premium ones (configuration will be taken from https://github.com/ibexa/admin-ui/blob/main/src/bundle/Resources/config/default_parameters.yaml#L2)
Also there is no need to change icon set per edition because we have one. (configuration will be taken from for example https://github.com/ibexa/recipes-dev/blob/master/ibexa/oss/5.0/config/packages/ibexa.yaml#L86) - I assume we do not have to specify it for "admin_group" and "default" is enough.
>  IBX-10139: Removed duplicated content type icons and icon sets definitions 

- ibexa/commerce/5.0/config/packages/league_oauth2_server.yaml
- ibexa/experience/5.0/config/packages/league_oauth2_server.yaml
- ibexa/headless/5.0/config/packages/league_oauth2_server.yaml
| :ticket: Issue | IBX-10292 |
In particular, this part:
```
persistence:
doctrine: null
```
messed up our custom persistance configuration from `ibexa_oauth2_server.yaml`.
In documentation, https://doc.ibexa.co/en/latest/users/oauth_server/#resource-server-configuration, that part is no longer valid. There is no need anymore for additional firewall - as mentioned in https://github.com/ibexa/recipes-dev/pull/135/files, all that should be required is to remove that oauth2 comment.
> IBX-10292: Commented out default league_oauth2_server configuration

- ibexa/commerce/5.0/manifest.json
- ibexa/experience/5.0/manifest.json
- ibexa/headless/5.0/manifest.json
| :ticket: Issue | IBX-10284 |
Aligned CACHE_NAMESPACE with ibexa/oss. 
N/A
N/A
> IBX-10284: Changed default CACHE_NAMESPACE from ezp to ibexa

- ibexa/commerce/5.0/manifest.json
- ibexa/experience/5.0/manifest.json
- ibexa/headless/5.0/manifest.json
- ibexa/oss/5.0/manifest.json
| :ticket: Issue | IBX-10640 |
Moved the `webpack.config.js` assets compilation (ibexa:encore:compile)  to the final step of the build process (auto-scripts). This ensures that backoffice code can be extended.
> IBX-10640: Changed order of assets compilation
